START TRANSACTION;
CREATE TABLE aiagentguildskill (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    guildid numeric(20,0) NOT NULL,
    name character varying(50) NOT NULL,
    instruction character varying(2000) NOT NULL,
    isenabled boolean NOT NULL,
    CONSTRAINT pk_aiagentguildskill PRIMARY KEY (id)
);

CREATE INDEX ix_aiagentguildskill_guildid ON aiagentguildskill (guildid);

CREATE UNIQUE INDEX ix_aiagentguildskill_guildid_name ON aiagentguildskill (guildid, name);

INSERT INTO "__EFMigrationsHistory" (migrationid, productversion)
VALUES ('20260407082035_ai-agent-skills', '9.0.1');

COMMIT;

