START TRANSACTION;
CREATE TABLE warntemplates (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    guildid numeric(20,0) NOT NULL,
    text text,
    dateadded timestamp without time zone,
    CONSTRAINT pk_warntemplates PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_warntemplates_guildid ON warntemplates (guildid);

INSERT INTO "__EFMigrationsHistory" (migrationid, productversion)
VALUES ('20260330200010_add-warn-template', '9.0.1');

COMMIT;

