START TRANSACTION;

CREATE TABLE logchannels (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    guildid numeric(20,0) NOT NULL,
    logtype integer NOT NULL,
    channelid numeric(20,0) NOT NULL,
    CONSTRAINT pk_logchannels PRIMARY KEY (id)
);

CREATE TABLE logignores (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    guildid numeric(20,0) NOT NULL,
    logitemid numeric(20,0) NOT NULL,
    itemtype integer NOT NULL,
    CONSTRAINT pk_logignores PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_logchannels_guildid_logtype ON logchannels (guildid, logtype);

CREATE UNIQUE INDEX ix_logignores_guildid_logitemid_itemtype ON logignores (guildid, logitemid, itemtype);

-- Migrate data: logsettings columns -> logchannels rows
INSERT INTO logchannels (guildid, logtype, channelid) SELECT guildid, 0, logotherid FROM logsettings WHERE logotherid IS NOT NULL;
INSERT INTO logchannels (guildid, logtype, channelid) SELECT guildid, 1, messageupdatedid FROM logsettings WHERE messageupdatedid IS NOT NULL;
INSERT INTO logchannels (guildid, logtype, channelid) SELECT guildid, 2, messagedeletedid FROM logsettings WHERE messagedeletedid IS NOT NULL;
INSERT INTO logchannels (guildid, logtype, channelid) SELECT guildid, 3, userjoinedid FROM logsettings WHERE userjoinedid IS NOT NULL;
INSERT INTO logchannels (guildid, logtype, channelid) SELECT guildid, 4, userleftid FROM logsettings WHERE userleftid IS NOT NULL;
INSERT INTO logchannels (guildid, logtype, channelid) SELECT guildid, 5, userbannedid FROM logsettings WHERE userbannedid IS NOT NULL;
INSERT INTO logchannels (guildid, logtype, channelid) SELECT guildid, 6, userunbannedid FROM logsettings WHERE userunbannedid IS NOT NULL;
INSERT INTO logchannels (guildid, logtype, channelid) SELECT guildid, 7, userupdatedid FROM logsettings WHERE userupdatedid IS NOT NULL;
INSERT INTO logchannels (guildid, logtype, channelid) SELECT guildid, 8, channelcreatedid FROM logsettings WHERE channelcreatedid IS NOT NULL;
INSERT INTO logchannels (guildid, logtype, channelid) SELECT guildid, 9, channeldestroyedid FROM logsettings WHERE channeldestroyedid IS NOT NULL;
INSERT INTO logchannels (guildid, logtype, channelid) SELECT guildid, 10, channelupdatedid FROM logsettings WHERE channelupdatedid IS NOT NULL;
INSERT INTO logchannels (guildid, logtype, channelid) SELECT guildid, 11, loguserpresenceid FROM logsettings WHERE loguserpresenceid IS NOT NULL;
INSERT INTO logchannels (guildid, logtype, channelid) SELECT guildid, 12, logvoicepresenceid FROM logsettings WHERE logvoicepresenceid IS NOT NULL;
INSERT INTO logchannels (guildid, logtype, channelid) SELECT guildid, 13, usermutedid FROM logsettings WHERE usermutedid IS NOT NULL;
INSERT INTO logchannels (guildid, logtype, channelid) SELECT guildid, 14, logwarnsid FROM logsettings WHERE logwarnsid IS NOT NULL;
INSERT INTO logchannels (guildid, logtype, channelid) SELECT guildid, 15, threaddeletedid FROM logsettings WHERE threaddeletedid IS NOT NULL;
INSERT INTO logchannels (guildid, logtype, channelid) SELECT guildid, 16, threadcreatedid FROM logsettings WHERE threadcreatedid IS NOT NULL;

-- Migrate data: ignoredlogchannels -> logignores (join to get guildid)
INSERT INTO logignores (guildid, logitemid, itemtype)
SELECT ls.guildid, ilc.logitemid, ilc.itemtype
FROM ignoredlogchannels ilc
JOIN logsettings ls ON ilc.logsettingid = ls.id;

DROP TABLE ignoredlogchannels;

DROP TABLE logsettings;

INSERT INTO "__EFMigrationsHistory" (migrationid, productversion)
VALUES ('20260403222105_log-channel-refactor', '9.0.1');

COMMIT;
