cant_dm: 我不能私訊你。確保您的 DM 已打開。轉到**設置->隱私&安全->允許來自伺服器成員的私人訊息**
color: 顏色
desc: 描述
empty_page: 本頁空白
error: 錯誤
error_occured: 發生了錯誤。
expr_import_invalid_data: 無法解析檔案，請確認是否為正確的 .yml 檔案
expr_import_no_input: 輸入錯誤，未找到正確的文字或檔案
expr_no_found_id: 未找到具有該 ID 的表達式。
hierarchy: 你不能對身分組階層高於或等於你的（或我的）用戶使用這個指令。
id: ID
insuf_perms_i: 我沒有足夠的權限。
insuf_perms_u: 您的權限不足。
invalid_input: 輸入錯誤
joined_discord: 已加入 Discord
joined_server: 已加入伺服器
leaderboard: 排行榜
members: 成員
msg_not_found: 未找到訊息。
must_be_in_voice: 你必須在這個伺服器上的語音頻道中
name: 名稱
no_channel_found: 找不到頻道。
no_search_results: 沒有搜尋結果。
no_user_on_this_page: 此頁面上沒有用戶。
not_enough: '你沒有足夠的 {0}'
not_found: 未找到。
not_in_voice: 您不在此伺服器上的語音頻道中。
owner: 擁有者
page: '第 {0} 頁'
perm_prevent: '#{0} {1} 阻止了此操作。'
price: 價格
prompt_no: "否"
prompt_yes: "是"
redacted_too_long: 訊息太長，已被刪減
response: 回覆
trigger: 觸發關鍵字詞
user_not_found: 未找到用戶。
userrole_icon_fail: 設定身分組圖示失敗。
userrole_icon_invalid: 身分組圖示不能為空。
userrole_icon_missing_permissions: 伺服器沒有使用身分組圖示的權限。
userrole_icon_success: '{0} 的圖示已儲存。'
users: 用戶
module: '模組：{0}'
options: 設定
overloads: 多載
requires: 需求
usage: 用法
