cant_dm: Eu não posso te mandar mensagem. Verifique que suas mensagens privadas estão abertas. Vá para **configurações -> Privacidade & Segurança -> Permitir mensagens diretas de membros do servidor**
color: Cor
desc: Descrição
empty_page: Essa página esta vazia.
error: Erro
error_occured: Ocorreu um erro.
expr_import_invalid_data: Incapaz de analisar arquivo. Verifique se é um arquivo .yml
expr_import_no_input: Entrada inválida. Nenhum arquivo ou entrada de texto válido encontrado.
expr_no_found_id: Não foi encontrada uma expressão com esse id.
hierarchy: Você não pode usar esse comando em usuários de cargo igual ou superior ao seu (ou meu) na hierarquia de cargos.
id: Id
insuf_perms_i: Não tenho permissões suficientes.
insuf_perms_u: Você não possui permissões suficientes.
invalid_input: Input inválida.
joined_discord: Entrou no Discord
joined_server: Entrou no servidor
leaderboard: Ranking
members: Membros
msg_not_found: Mensagem não encontrada.
must_be_in_voice: Você precisa estar em um canal de voz nesse servidor.
name: Nome
no_channel_found: Nenhum canal encontrado.
no_search_results: Nenhum resultado de pesquisa.
no_user_on_this_page: Nenhum usuário nessa página.
not_enough: 'Você não tem {0} suficiente.'
not_found: Não encontrado.
not_in_voice: Você não está em um canal de voz nesse servidor.
owner: Dono
page: 'Página {0}'
perm_prevent: 'Permissão número #{0} {1} está impedindo essa ação.'
price: Preço
prompt_no: "Não"
prompt_yes: "Sim"
redacted_too_long: O texto é longo demais.
response: Resposta
trigger: Gatilho
user_not_found: Usuário não encontrado.
userrole_icon_fail: Falha ao definir o ícone do cargo.
userrole_icon_invalid: O ícone do cargo não pode estar vazio.
userrole_icon_missing_permissions: O servidor não tem permissão para usar ícones de cargo.
userrole_icon_success: 'O ícone de {0} foi salvo.'
users: Usuários
module: 'Módulo: {0}'
options: Opções
overloads: Sobrecargas
requires: Requer
usage: Uso
