cant_dm: Je ne peux pas te dm. Assure-toi que tes MP sont ouverts. Va dans **options (bouton en forme de rouage) -> Confidentialité et sécurité -> Autoriser les messages directs des membres du serveur**
color: Couleur
desc: Description
empty_page: Cette page est vide.
error: Erreur
error_occured: Une erreur est survenue.
expr_import_invalid_data: Impossible d'analyser le fichier. Assurez-vous qu'il s'agisse d'un fichier .yml
expr_import_no_input: Saisie invalide. Aucun chargement de fichier ou saisie de texte trouvé.
expr_no_found_id: Aucune expression de trouvée avec cet id.
hierarchy: Vous ne pouvez pas utiliser cette commande sur des membres ayant un rôle supérieur ou égal au vôtre dans la hiérarchie.
id: Id
insuf_perms_i: Mes permissions sont insuffisantes.
insuf_perms_u: Vos permissions sont insuffisantes.
invalid_input: Entrée invalide.
joined_discord: A rejoint Discord
joined_server: A rejoint le serveur
leaderboard: Classement
members: Membres
msg_not_found: Message introuvable.
must_be_in_voice: Vous avez besoin d'être dans un salon vocal de ce serveur.
name: Nom
no_channel_found: Aucun salon trouvé.
no_search_results: Aucuns résultats de recherche
no_user_on_this_page: Aucun membre sur cette page.
not_enough: 'Vous n''avez pas assez de {0}'
not_found: Introuvable.
not_in_voice: Vous n'êtes pas dans un salon vocal sur ce serveur.
owner: Propriétaire
page: 'page {0}'
perm_prevent: 'Le numéro d''autorisation # {0} {1} empêche cette action.'
price: Prix
redacted_too_long: Révisé car trop long.
response: Réponse
trigger: Déclencheur
user_not_found: Utilisateur introuvable.
userrole_icon_fail: Échec de la définition de l'icône du rôle.
userrole_icon_invalid: L'icône du rôle ne peut pas être vide.
userrole_icon_missing_permissions: Le serveur n'a pas les permissions pour utiliser les icônes de rôle.
userrole_icon_success: 'L''icône de {0} a été sauvegardée.'
users: Membres
module: 'Module: {0}'
options: Options
overloads: Surcharges
requires: Requiert
usage: Usage
