cant_dm: DMを送信できません。DMが開放されていることを確認してください。**設定（歯車ボタン）→プライバシー・安全→サーバーメンバーからのダイレクトメッセージを許可**
color: 色
desc: 説明
empty_page: このページは空です。
error: エラー
error_occured: エラーが発生しました。
expr_import_invalid_data: ファイルを解析できません。有効な.ymlファイルであることを確認してください
expr_import_no_input: 無効な入力です。有効なファイルアップロードまたは入力テキストが見つかりません
expr_no_found_id: そのIDの式が見つかりません。
hierarchy: このコマンドは、自分の役割と同等か、それ以上の役割を持つユーザーには使用できません。
id: ID
insuf_perms_i: Botに十分な権限がありません。
insuf_perms_u: あなたに十分な権限がありません。
invalid_input: 不適切な入力。
joined_discord: Discord参加日
joined_server: サーバー参加日
leaderboard: リーダーボード
members: メンバー数
msg_not_found: メッセージが見つかりません。
must_be_in_voice: このサーバーのボイスチャンネルにいる必要があります。
name: 名前
no_channel_found: チャンネルが見つかりませんでした。
no_search_results: 検索結果はありません。
no_user_on_this_page: このページにユーザーはいません。
not_enough: '{0}が足りません'
not_found: 見つかりません。
not_in_voice: あなたはこのサーバー上の音声チャネルにいません。
owner: オーナー
page: '{0}ページ'
perm_prevent: '権限番号#{0} {1}がこのアクションを妨げています。'
price: 価格
redacted_too_long: 非常に長いので編集されました。
response: 反応
trigger: トリガー
user_not_found: ユーザーが見つかりません。
userrole_icon_fail: ロールアイコンの設定に失敗しました。
userrole_icon_invalid: ロールアイコンは空にできません。
userrole_icon_missing_permissions: サーバーにロールアイコンを使用する権限がありません。
userrole_icon_success: '{0}のアイコンが保存されました。'
users: ユーザー
module: 'モジュール: {0}'
options: ''
overloads: オーバーロード
requires: ''
usage: 使用方法
