cant_dm: DM을 보낼 수 없어요. DM이 열려 있는지 확인해 주세요. **설정(톱니바퀴 버튼) -> 개인정보 보호 및 보안 -> 서버 멤버로부터의 다이렉트 메시지 허용**을 켜 주세요.
color: 색상
desc: 설명
empty_page: 이 페이지는 비어 있어요.
error: 오류
error_occured: 오류가 발생했어요.
expr_import_invalid_data: 파일을 파싱할 수 없어요. 유효한 .yml 파일인지 확인해 주세요.
expr_import_no_input: 잘못된 입력이에요. 유효한 파일 업로드 또는 입력 텍스트를 찾을 수 없어요.
expr_no_found_id: 해당 ID의 표현식을 찾을 수 없어요.
hierarchy: 역할 계층에서 자신(또는 봇)보다 높거나 같은 역할을 가진 유저에게는 이 명령어를 사용할 수 없어요.
id: ID
insuf_perms_i: 봇의 권한이 부족해요.
insuf_perms_u: 당신의 권한이 부족해요.
invalid_input: 잘못된 입력이에요.
joined_discord: Discord 가입일
joined_server: 서버 가입일
leaderboard: 리더보드
members: 멤버
msg_not_found: 메시지를 찾을 수 없어요.
must_be_in_voice: 이 서버의 음성 채널에 접속해 있어야 해요.
name: 이름
no_channel_found: 채널을 찾을 수 없어요.
no_search_results: 검색 결과가 없어요.
no_user_on_this_page: 이 페이지에 유저가 없어요.
not_enough: '{0}이(가) 부족해요.'
not_found: 찾을 수 없어요.
not_in_voice: 이 서버의 음성 채널에 접속해 있지 않아요.
owner: 소유자
page: '페이지 {0}'
perm_prevent: '권한 #{0} {1}이(가) 이 동작을 막고 있어요.'
price: 가격
prompt_no: "아니요"
prompt_yes: "네"
redacted_too_long: 내용이 너무 길어서 생략되었어요.
response: 응답
trigger: 트리거
user_not_found: 유저를 찾을 수 없어요.
userrole_icon_fail: 역할 아이콘 설정에 실패했어요.
userrole_icon_invalid: 역할 아이콘은 비워둘 수 없어요.
userrole_icon_missing_permissions: 서버에 역할 아이콘을 사용할 권한이 없어요.
userrole_icon_success: '{0}의 아이콘이 저장되었어요.'
users: 유저
module: '모듈: {0}'
options: 옵션
overloads: 오버로드
requires: 필요 조건
usage: 사용법
