cant_dm: I can't DM you. Make sure your DMs are open. Go to **options (cog button) -> Privacy & Safety -> Allow direct messages from server members**
color: Color
desc: Description
empty_page: This page is empty.
error: Error
error_occured: An error occurred. Not my fault.
expr_import_invalid_data: Unable to parse the file. Make sure it's a valid .yml file.
expr_import_no_input: Invalid input. No valid file upload or input text found.
expr_no_found_id: No expression found with that id.
hierarchy: You can't use this command on users with a role higher or equal than yours (or mine) in the role hierarchy. Hmph, I don't make the rules.
id: Id
insuf_perms_i: I have insufficient permissions. It's not a strength issue, okay?
insuf_perms_u: You have insufficient permissions. Don't even try.
invalid_input: Invalid input. Try again properly.
joined_discord: Joined Discord
joined_server: Joined server
leaderboard: Leaderboard
members: Members
msg_not_found: Message not found.
must_be_in_voice: You need to be in a voice channel on this server.
name: Name
no_channel_found: No channel found.
no_search_results: No search results.
no_user_on_this_page: No users on this page.
not_enough: 'You don''t have enough {0}.'
not_found: Not found.
not_in_voice: You're not in a voice channel on this server.
owner: Owner
page: 'page {0}'
perm_prevent: 'Permission number #{0} {1} is preventing this action.'
price: Price
redacted_too_long: Redacted because it's too long.
response: Response
trigger: Trigger
user_not_found: User not found. B-baka, are you sure they exist?
userrole_icon_fail: Failed to set the role icon.
userrole_icon_invalid: The role icon cannot be empty. Don't waste my time.
userrole_icon_missing_permissions: The server does not have permissions to use RoleIcons.
userrole_icon_success: 'The icon for {0} has been saved.'
users: Users
module: 'Module: {0}'
options: Options
overloads: Overloads
requires: Requires
usage: Usage
