cant_dm: Я не можу надіслати тобі особисте повідомлення. Переконайся, що DM відкриті. Перейди до **налаштувань (кнопка шестерінки) -> Конфіденційність -> Дозволити особисті повідомлення від учасників сервера**
color: Колір
desc: Опис
empty_page: Ця сторінка порожня.
error: Помилка
error_occured: Сталася помилка.
expr_import_invalid_data: Неможливо розібрати файл. Переконайся, що це валідний .yml файл
expr_import_no_input: Невірний ввід. Не знайдено валідного файлу або тексту.
expr_no_found_id: Не знайдено виразу з таким id.
hierarchy: Ти не можеш використовувати цю команду на користувачах з роллю вищою або рівною твоїй (або моїй) в ієрархії ролей.
id: Id
insuf_perms_i: У мене недостатньо прав.
insuf_perms_u: У тебе недостатньо прав.
invalid_input: Невірний ввід.
joined_discord: Приєднався до Discord
joined_server: Приєднався до сервера
leaderboard: Таблиця лідерів
members: Учасники
msg_not_found: Повідомлення не знайдено.
must_be_in_voice: Ти маєш бути в голосовому каналі на цьому сервері.
name: Назва
no_channel_found: Канал не знайдено.
no_search_results: Нічого не знайдено.
no_user_on_this_page: Немає користувачів на цій сторінці.
not_enough: 'У тебе недостатньо {0}'
not_found: Не знайдено.
not_in_voice: Ти не в голосовому каналі на цьому сервері.
owner: Власник
page: 'сторінка {0}'
perm_prevent: 'Дозвіл #{0} {1} блокує цю дію.'
price: Ціна
redacted_too_long: Приховано, бо занадто довге.
response: Відповідь
trigger: Тригер
user_not_found: Користувача не знайдено.
userrole_icon_fail: Не вдалося встановити іконку ролі.
userrole_icon_invalid: Іконка ролі не може бути порожньою.
userrole_icon_missing_permissions: Сервер не має прав на використання іконок ролей.
userrole_icon_success: 'Іконку для {0} збережено.'
users: Користувачі
module: 'Модуль: {0}'
options: Параметри
overloads: Перевантаження
requires: Потрібно
usage: Використання
