cant_dm: Sana DM atamıyorum. DM'lerinin açık olduğundan emin ol. **Ayarlar (çark butonu) -> Gizlilik ve Güvenlik -> Sunucu üyelerinden gelen doğrudan mesajlara izin ver** seçeneğini aç.
color: Renk
desc: Açıklama
empty_page: Bu sayfa boş.
error: Hata
error_occured: Bir hata oluştu.
expr_import_invalid_data: Dosya ayrıştırılamadı. Geçerli bir .yml dosyası olduğundan emin ol.
expr_import_no_input: Geçersiz girdi. Geçerli bir dosya yüklemesi veya girdi metni bulunamadı.
expr_no_found_id: Bu id ile bir ifade bulunamadı.
hierarchy: Bu komutu rol hiyerarşisinde senden (veya benden) daha yüksek veya eşit bir role sahip kullanıcılarda kullanamazsın.
id: Id
insuf_perms_i: Yeterli izinlerim yok.
insuf_perms_u: Yeterli izinlerin yok.
invalid_input: Geçersiz girdi.
joined_discord: Discord'a katıldı
joined_server: Sunucuya katıldı
leaderboard: Sıralama
members: Üyeler
msg_not_found: Mesaj bulunamadı.
must_be_in_voice: Bu sunucuda bir sesli kanalda olmalısın.
name: İsim
no_channel_found: Kanal bulunamadı.
no_search_results: Arama sonucu bulunamadı.
no_user_on_this_page: Bu sayfada kullanıcı yok.
not_enough: 'Yeterli {0} sahip değilsin'
not_found: Bulunamadı.
not_in_voice: Bu sunucuda bir sesli kanalda değilsin.
owner: Sahip
page: 'sayfa {0}'
perm_prevent: '{0} numaralı {1} izni bu işlemi engelliyor.'
price: Fiyat
prompt_no: "Hayır"
prompt_yes: "Evet"
redacted_too_long: Çok uzun olduğu için gizlendi.
response: Yanıt
trigger: Tetikleyici
user_not_found: Kullanıcı bulunamadı.
userrole_icon_fail: Rol simgesi ayarlanamadı.
userrole_icon_invalid: Rol simgesi boş olamaz.
userrole_icon_missing_permissions: Sunucunun RoleIcons kullanma izni yok.
userrole_icon_success: '{0} için simge kaydedildi.'
users: Kullanıcılar
module: 'Modül: {0}'
options: Seçenekler
overloads: Aşırı yüklemeler
requires: Gerektirir
usage: Kullanım
