cant_dm: No puedo mensajearte por privado. Comprueba que tus MD están abiertos. Ve a **opciones (botón del engranaje) -> Privacidad y seguridad -> Permitir mensajes directos de los miembros del servidor**
color: Color
desc: Descripción
empty_page: Esta página está vacía.
error: Error
error_occured: Un error ocurrió.
expr_import_invalid_data: No se puede analizar el archivo, asegúrese que sea un archivo .yml válido.
expr_import_no_input: Entrada no válida. No se ha encontrado ningún archivo o texto de entrada válido.
expr_no_found_id: No existen expresiones con esa ID.
hierarchy: No puedes usar este comando en usuarios con un rol más alto o igual al tuyo.
id: ID
insuf_perms_i: No tengo suficientes permisos.
insuf_perms_u: No tienes los suficientes permisos.
invalid_input: Entrada no válida.
joined_discord: Ingresó a Discord
joined_server: Ingresó al servidor
leaderboard: Marcador
members: Miembros
msg_not_found: Mensaje no encontrado.
must_be_in_voice: Debes estar en un canal de voz en este servidor.
name: Nombre
no_channel_found: Canal no encontrado.
no_search_results: No hubo resultados de búsqueda.
no_user_on_this_page: No hay usuarios en esta página.
not_enough: 'No tienes suficientes {0}.'
not_found: No encontrada.
not_in_voice: No estás en un canal de voz en este servidor.
owner: Dueño
page: 'Página {0}'
perm_prevent: 'El permiso número #{0} {1} está impidiendo esta acción.'
price: Precio
prompt_no: "No"
prompt_yes: "Sí"
redacted_too_long: Editada porque es muy larga.
response: Respuesta
trigger: Escribe
user_not_found: Usuario no encontrado.
userrole_icon_fail: Error al establecer el ícono del rol.
userrole_icon_invalid: El ícono del rol no puede estar vacío.
userrole_icon_missing_permissions: El servidor no tiene permisos para usar íconos de rol.
userrole_icon_success: 'El ícono de {0} ha sido guardado.'
users: Usuarios
module: 'Módulo: {0}'
options: Opciones
overloads: Sobrecargas
requires: Requiere
usage: Modo de uso
