cant_dm: Не могу да ти пошаљем поруку. Провери да ли су ти DM-ови отворени. Иди на **опције (дугме зупчаник) -> Приватност и безбедност -> Дозволи директне поруке од чланова сервера**
color: Боја
desc: Опис
empty_page: Ова страница је празна.
error: Грешка
error_occured: Догодила се грешка.
expr_import_invalid_data: Не могу да парсирам фајл. Провери да ли је валидан .yml фајл
expr_import_no_input: Неисправан унос. Није пронађен валидан фајл или текст.
expr_no_found_id: Није пронађен израз са тим ID-ом.
hierarchy: Не можеш да користиш ову команду на корисницима са улогом вишом или једнаком твојој (или мојој) у хијерархији улога.
id: Id
insuf_perms_i: Немам довољно дозвола.
insuf_perms_u: Немаш довољно дозвола.
invalid_input: Неисправан унос.
joined_discord: Придружио се Discord-у
joined_server: Придружио се серверу
leaderboard: Табела
members: Чланови
msg_not_found: Порука није пронађена.
must_be_in_voice: Мораш бити у гласовном каналу на овом серверу.
name: Име
no_channel_found: Канал није пронађен.
no_search_results: Нема резултата претраге.
no_user_on_this_page: Нема корисника на овој страници.
not_enough: 'Немаш довољно {0}'
not_found: Није пронађено.
not_in_voice: Ниси у гласовном каналу на овом серверу.
owner: Власник
page: 'страница {0}'
perm_prevent: 'Дозвола број #{0} {1} спречава ову акцију.'
price: Цена
redacted_too_long: Уклоњено јер је предугачко.
response: Одговор
trigger: Окидач
user_not_found: Корисник није пронађен.
userrole_icon_fail: Постављање иконе улоге није успело.
userrole_icon_invalid: Икона улоге не може бити празна.
userrole_icon_missing_permissions: Сервер нема дозволе за коришћење икона улога.
userrole_icon_success: 'Икона за {0} је сачувана.'
users: Корисници
module: 'Модул: {0}'
options: Опције
overloads: Преоптерећења
requires: Захтева
usage: Употреба
