cant_dm: Tôi không thể nhắn tin riêng cho bạn. Hãy đảm bảo DM của bạn đang mở. Vào **tùy chọn (nút bánh răng) -> Quyền riêng tư & An toàn -> Cho phép tin nhắn trực tiếp từ thành viên server**
color: Màu sắc
desc: Mô tả
empty_page: Trang này trống.
error: Lỗi
error_occured: Đã xảy ra lỗi.
expr_import_invalid_data: Không thể phân tích tệp. Hãy đảm bảo đó là tệp .yml hợp lệ
expr_import_no_input: Đầu vào không hợp lệ. Không tìm thấy tệp tải lên hoặc nội dung hợp lệ.
expr_no_found_id: Không tìm thấy biểu thức với id đó.
hierarchy: Bạn không thể dùng lệnh này trên người dùng có vai trò cao hơn hoặc bằng bạn (hoặc tôi) trong bậc vai trò.
id: Id
insuf_perms_i: Tôi không có đủ quyền.
insuf_perms_u: Bạn không có đủ quyền.
invalid_input: Đầu vào không hợp lệ.
joined_discord: Ngày tham gia Discord
joined_server: Ngày tham gia server
leaderboard: Bảng xếp hạng
members: Thành viên
msg_not_found: Không tìm thấy tin nhắn.
must_be_in_voice: Bạn cần ở trong một kênh thoại trên server này.
name: Tên
no_channel_found: Không tìm thấy kênh.
no_search_results: Không có kết quả tìm kiếm.
no_user_on_this_page: Không có người dùng trên trang này.
not_enough: 'Bạn không có đủ {0}'
not_found: Không tìm thấy.
not_in_voice: Bạn không ở trong kênh thoại trên server này.
owner: Chủ sở hữu
page: 'trang {0}'
perm_prevent: 'Quyền số #{0} {1} đang ngăn hành động này.'
price: Giá
prompt_no: "Không"
prompt_yes: "Có"
redacted_too_long: Đã ẩn vì quá dài.
response: Phản hồi
trigger: Kích hoạt
user_not_found: Không tìm thấy người dùng.
userrole_icon_fail: Không thể đặt biểu tượng vai trò.
userrole_icon_invalid: Biểu tượng vai trò không được để trống.
userrole_icon_missing_permissions: Server không có quyền sử dụng biểu tượng vai trò.
userrole_icon_success: 'Biểu tượng cho {0} đã được lưu.'
users: Người dùng
module: 'Mô-đun: {0}'
options: Tùy chọn
overloads: Cách dùng khác
requires: Yêu cầu
usage: Cách dùng
