cant_dm: Ich kann keine Nachrichten an dich senden. Stelle sicher, dass deine Direktnachrichten öffentlich sind. Gehe zu **Benutzereinstellungen (Zahnrad) ->  Privatsphäre & Sicherheit -> Direktnachrichten von Servermitgliedern erlauben**
color: Farbe
desc: Beschreibung
empty_page: Diese Seite ist leer.
error: Fehler
error_occured: Ein Fehler ist aufgetreten.
expr_import_invalid_data: Kann Datei nicht Analysieren. Stelle sicher, dass es eine gültige .yml Datei ist
expr_import_no_input: Ungültiger Input. Kein gültiger Dateiupload oder Input Text gefunden.
expr_no_found_id: ''
hierarchy: Du kannst diesen Command nicht an einen Nutzer mit einem höheren oder gleichwertigen Rang in der Hierarchi ausführen.
id: Id
insuf_perms_i: Ich habe unzureichende Berechtigungen.
insuf_perms_u: Du hast unzureichende Berechtigungen.
invalid_input: Ungültige Eingabe.
joined_discord: ist Discord beigetreten
joined_server: ist dem Server beigetreten
leaderboard: Rangliste
members: Mitglieder
msg_not_found: Nachricht wurde nicht gefunden.
must_be_in_voice: Du musst in einem Sprachkanal sein auf diesem Server.
name: Name
no_channel_found: Keinen Channel gefunden.
no_search_results: Keine Suchergebnisse.
no_user_on_this_page: Keine Nutzer auf dieser Seite.
not_enough: 'Du hast nicht genug {0}'
not_found: Nicht gefunden.
not_in_voice: Du bist nicht in einem Sprachkanal auf diesem Server.
owner: Besitzer
page: 'Seite {0}'
perm_prevent: 'Berechtigung Nummer #{0} {1} verhindert diese Aktion.'
price: Preis
prompt_no: "Nein"
prompt_yes: "Ja"
redacted_too_long: Wurde entfernt da es zu lang ist.
response: Antwort
trigger: Auslöser
user_not_found: Nutzer nicht gefunden.
userrole_icon_fail: Fehler beim Festlegen des Rollensymbols.
userrole_icon_invalid: Das Rollensymbol darf nicht leer sein.
userrole_icon_missing_permissions: Der Server hat keine Berechtigung zur Verwendung von Rollensymbolen.
userrole_icon_success: 'Das Symbol für {0} wurde gespeichert.'
users: Nutzer
module: 'Modul: {0}'
options: Optionen
overloads: Überladungen
requires: Benötigt
usage: Nutzung
