cant_dm: Aku nggak bisa kirim DM ke kamu. Pastikan DM kamu terbuka. Pergi ke **opsi (tombol gerigi) -> Privasi & Keamanan -> Izinkan pesan langsung dari anggota server**
color: Warna
desc: Deskripsi
empty_page: Halaman ini kosong.
error: Error
error_occured: Terjadi error.
expr_import_invalid_data: Tidak bisa memproses file tersebut. Pastikan file-nya adalah file .yml yang valid
expr_import_no_input: Input tidak valid. Tidak ditemukan file upload atau teks input yang valid.
expr_no_found_id: Tidak ditemukan ekspresi dengan id tersebut.
hierarchy: Kamu nggak bisa menggunakan perintah ini pada pengguna yang memiliki role lebih tinggi atau setara dengan kamu (atau aku) di hierarki role.
id: Id
insuf_perms_i: Aku tidak punya izin yang cukup.
insuf_perms_u: Kamu tidak punya izin yang cukup.
invalid_input: Input tidak valid.
joined_discord: Bergabung di Discord
joined_server: Bergabung di server
leaderboard: Papan Peringkat
members: Anggota
msg_not_found: Pesan tidak ditemukan.
must_be_in_voice: Kamu harus berada di channel suara di server ini.
name: Nama
no_channel_found: Channel tidak ditemukan.
no_search_results: Tidak ada hasil pencarian.
no_user_on_this_page: Tidak ada pengguna di halaman ini.
not_enough: 'Kamu nggak punya cukup {0}'
not_found: Tidak ditemukan.
not_in_voice: Kamu tidak berada di channel suara di server ini.
owner: Pemilik
page: 'halaman {0}'
perm_prevent: 'Izin nomor #{0} {1} mencegah tindakan ini.'
price: Harga
prompt_no: "Tidak"
prompt_yes: "Ya"
redacted_too_long: Disembunyikan karena terlalu panjang.
response: Respons
trigger: Pemicu
user_not_found: Pengguna tidak ditemukan.
userrole_icon_fail: Gagal mengatur ikon role.
userrole_icon_invalid: Ikon role tidak boleh kosong.
userrole_icon_missing_permissions: Server tidak memiliki izin untuk menggunakan RoleIcons.
userrole_icon_success: 'Ikon untuk {0} telah disimpan.'
users: Pengguna
module: 'Modul: {0}'
options: Opsi
overloads: Overload
requires: Membutuhkan
usage: Penggunaan
