cant_dm: Я не могу отправить ЛС. Убедитесь, что ваши ЛС открыты. Перейдите в ** параметры (кнопка с шестеренкой) -> Конфиденциальность и безопасность -> Разрешить прямые сообщения от участников сервера **
color: Цвет
desc: Описание
empty_page: Эта страница пуста.
error: Ошибка
error_occured: Произошла ошибка.
expr_import_invalid_data: Невозможно проанализировать файл. Убедитесь, что это действительный файл .yml
expr_import_no_input: Некорректный ввод. Не найдено ни одного допустимого файла для загрузки или ввода текста.
expr_no_found_id: ''
hierarchy: Вы не можете использовать эту команду на пользователя с высшей или такой же ролью как у вас по правилам иерархии ролей.
id: Идентификатор
insuf_perms_i: У меня недостаточно прав.
insuf_perms_u: У вас недостаточно прав.
invalid_input: Неправильное значение
joined_discord: Зарегистрировался в Дискорде
joined_server: Зашел на сервер
leaderboard: Таблица лидеров
members: Участники
msg_not_found: Сообщение не найдено.
must_be_in_voice: Вам нужно быть в голосовом канале на этом сервере.
name: Имя
no_channel_found: Канал не найден.
no_search_results: Никаких результатов поиска не найдено.
no_user_on_this_page: На этой странице нет пользователей.
not_enough: 'У вас не хватает {0}'
not_found: Не найдено.
not_in_voice: Вы не находитесь в голосом канале на этом сервере
owner: Владелец
page: 'Страница {0}'
perm_prevent: 'Разрешение {1} под номером {0} предотвращает данное действие.'
price: Цена
prompt_no: "Нет"
prompt_yes: "Да"
redacted_too_long: Отредактировано, из-за того, что оно слишком длинное.
response: Отклик
trigger: Тригер
user_not_found: Пользователь не найден.
userrole_icon_fail: Не удалось установить иконку роли.
userrole_icon_invalid: Иконка роли не может быть пустой.
userrole_icon_missing_permissions: У сервера нет прав для использования иконок ролей.
userrole_icon_success: 'Иконка для {0} была сохранена.'
users: Пользователи
module: 'Модуль: {0}'
options: Параметры
overloads: Перегрузки
requires: Требуются
usage: Использование
