cant_dm: Nie mogę wysłać ci wiadomości prywatnej. Upewnij się, że masz otwarte DM. Przejdź do **opcje (przycisk koła zębatego) -> Prywatność i bezpieczeństwo -> Zezwalaj na wiadomości bezpośrednie od członków serwera**
color: Kolor
desc: Opis
empty_page: Ta strona jest pusta.
error: Błąd
error_occured: Wystąpił błąd.
expr_import_invalid_data: Nie udało się przetworzyć pliku. Upewnij się, że to prawidłowy plik .yml
expr_import_no_input: Nieprawidłowe dane wejściowe. Nie znaleziono prawidłowego pliku ani tekstu.
expr_no_found_id: Nie znaleziono wyrażenia o tym id.
hierarchy: Nie możesz użyć tej komendy na użytkownikach z rolą wyższą lub równą twojej (lub mojej) w hierarchii ról.
id: Id
insuf_perms_i: Mam niewystarczające uprawnienia.
insuf_perms_u: Masz niewystarczające uprawnienia.
invalid_input: Nieprawidłowe dane wejściowe.
joined_discord: Dołączył do Discorda
joined_server: Dołączył do serwera
leaderboard: Ranking
members: Członkowie
msg_not_found: Nie znaleziono wiadomości.
must_be_in_voice: Musisz być na kanale głosowym na tym serwerze.
name: Nazwa
no_channel_found: Nie znaleziono kanału.
no_search_results: Brak wyników wyszukiwania.
no_user_on_this_page: Brak użytkowników na tej stronie.
not_enough: 'Nie masz wystarczająco {0}'
not_found: Nie znaleziono.
not_in_voice: Nie jesteś na kanale głosowym na tym serwerze.
owner: Właściciel
page: 'strona {0}'
perm_prevent: 'Uprawnienie nr #{0} {1} blokuje tę akcję.'
price: Cena
prompt_no: "Nie"
prompt_yes: "Tak"
redacted_too_long: Ukryto, bo jest za długie.
response: Odpowiedź
trigger: Wyzwalacz
user_not_found: Nie znaleziono użytkownika.
userrole_icon_fail: Nie udało się ustawić ikony roli.
userrole_icon_invalid: Ikona roli nie może być pusta.
userrole_icon_missing_permissions: Serwer nie ma uprawnień do używania ikon ról.
userrole_icon_success: 'Ikona dla {0} została zapisana.'
users: Użytkownicy
module: 'Moduł: {0}'
options: Opcje
overloads: Przeciążenia
requires: Wymaga
usage: Użycie
