cant_dm: لا أستطيع إرسال رسالة خاصة لك. تأكد من أن الرسائل الخاصة مفتوحة. اذهب إلى **الخيارات (زر الترس) -> الخصوصية والأمان -> السماح بالرسائل المباشرة من أعضاء السيرفر**
color: اللون
desc: الوصف
empty_page: هذه الصفحة فارغة.
error: خطأ
error_occured: حدث خطأ.
expr_import_invalid_data: تعذر تحليل الملف. تأكد من أنه ملف .yml صالح
expr_import_no_input: إدخال غير صالح. لم يتم العثور على ملف مرفوع أو نص إدخال صالح.
expr_no_found_id: لم يتم العثور على تعبير بهذا المعرف.
hierarchy: لا يمكنك استخدام هذا الأمر على مستخدمين لديهم دور أعلى أو مساوٍ لدورك (أو دوري) في تسلسل الأدوار.
id: المعرف
insuf_perms_i: ليس لدي صلاحيات كافية.
insuf_perms_u: ليس لديك صلاحيات كافية.
invalid_input: إدخال غير صالح.
joined_discord: تاريخ الانضمام إلى Discord
joined_server: تاريخ الانضمام إلى السيرفر
leaderboard: لوحة المتصدرين
members: الأعضاء
msg_not_found: الرسالة غير موجودة.
must_be_in_voice: يجب أن تكون في قناة صوتية في هذا السيرفر.
name: الاسم
no_channel_found: لم يتم العثور على قناة.
no_search_results: لا توجد نتائج بحث.
no_user_on_this_page: لا يوجد مستخدمون في هذه الصفحة.
not_enough: 'ليس لديك ما يكفي من {0}'
not_found: غير موجود.
not_in_voice: أنت لست في قناة صوتية في هذا السيرفر.
owner: المالك
page: 'الصفحة {0}'
perm_prevent: 'الصلاحية رقم #{0} {1} تمنع هذا الإجراء.'
price: السعر
prompt_no: "لا"
prompt_yes: "نعم"
redacted_too_long: تم الحذف لأنه طويل جداً.
response: الاستجابة
trigger: المُحفّز
user_not_found: المستخدم غير موجود.
userrole_icon_fail: فشل في تعيين أيقونة الدور.
userrole_icon_invalid: لا يمكن أن تكون أيقونة الدور فارغة.
userrole_icon_missing_permissions: السيرفر لا يملك صلاحيات استخدام أيقونات الأدوار.
userrole_icon_success: 'تم حفظ الأيقونة للدور {0}.'
users: المستخدمون
module: 'الوحدة: {0}'
options: الخيارات
overloads: الاستخدامات البديلة
requires: يتطلب
usage: الاستخدام
