using System.CodeDom.Compiler;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace NadekoBot.Generators;

/// <summary>
/// Source generator that turns [AiTool]-attributed methods on adapter classes
/// (IAiToolGroup / IAiCoreToolGroup implementers) into IAiTool implementations.
///
/// The generated class is a thin wrapper that:
///  1. Validates the LLM-supplied JsonElement arguments
///  2. Runs declarative permission checks ([AiRequiresPerm] etc.)
///  3. Calls the adapter method
///  4. Serialises the result (or passes Task&lt;string&gt; through verbatim)
///  5. Catches ToolException and emits a stable {"error","message"} JSON
/// </summary>
[Generator]
public sealed class AiToolGenerator : IIncrementalGenerator
{
    private const string AiToolAttr = "NadekoBot.AiAgent.AiToolAttribute";
    private const string ToolExceptionType = "NadekoBot.Modules.Utility.AiAgent.ToolException";
    private const string JsonOptionsType = "NadekoBot.Modules.Utility.AiAgent.AiToolJsonOptions";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var methods = context.SyntaxProvider.ForAttributeWithMetadataName(
            AiToolAttr,
            static (node, _) => node is MethodDeclarationSyntax,
            static (ctx, _) => ToolMethodInfo.From(ctx));

        var collected = methods
            .Where(static m => m is not null)
            .Collect();

        context.RegisterSourceOutput(collected, static (spc, methods) =>
        {
            if (methods.IsDefaultOrEmpty)
                return;

            EmitSharedHelpers(spc);

            foreach (var method in methods)
                EmitToolClass(spc, method!);
        });
    }

    private static void EmitSharedHelpers(SourceProductionContext spc)
    {
        const string src = """
            // <auto-generated/>
            #nullable enable
            using System.Text.Json;
            using System.Text.Json.Serialization;

            namespace NadekoBot.Modules.Utility.AiAgent;

            /// <summary>
            /// Shared serializer settings for generated AI tool wrappers.
            /// </summary>
            internal static class AiToolJsonOptions
            {
                /// <summary>
                /// snake_case property naming, case-insensitive matching, and "123" -> int coercion
                /// so the LLM can be sloppy with arg shape and we still get a clean DTO.
                /// </summary>
                public static JsonSerializerOptions Options { get; } = new()
                {
                    PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower,
                    PropertyNameCaseInsensitive = true,
                    NumberHandling = JsonNumberHandling.AllowReadingFromString
                };

                /// <summary>
                /// Reusable empty arguments element. Some LLMs send no args at all for
                /// zero-arg tool calls; generated wrappers fall back to this instead of
                /// allocating a JsonDocument per invocation.
                /// </summary>
                public static JsonElement EmptyObject { get; } =
                    JsonDocument.Parse("{}").RootElement;

                /// <summary>
                /// True if a JSON element is present (not Null, not Undefined).
                /// </summary>
                public static bool IsPresent(JsonElement e)
                    => e.ValueKind is not JsonValueKind.Null and not JsonValueKind.Undefined;
            }
            """;

        spc.AddSource("AiToolJsonOptions.g.cs", SourceText.From(src, Encoding.UTF8));
    }

    private static void EmitToolClass(SourceProductionContext spc, ToolMethodInfo method)
    {
        var className = $"{method.ContainingTypeShort}_{method.MethodName}_AiTool";

        var schemaJson = SchemaBuilder.BuildToolSchema(method);

        var sb = new StringBuilder(2048);
        using (var sw = new StringWriter(sb))
        using (var w = new IndentedTextWriter(sw))
        {
            w.WriteLine("// <auto-generated/>");
            w.WriteLine("#nullable enable");
            w.WriteLine();
            w.WriteLine("using System.Text.Json;");
            w.WriteLine("using NadekoBot.Modules.Utility.AiAgent;");
            w.WriteLine("using static NadekoBot.Modules.Utility.AiAgent.AiToolJsonOptions;");
            w.WriteLine();
            w.WriteLine($"namespace {method.ContainingNamespace};");
            w.WriteLine();
            w.WriteLine($"public sealed class {className}({method.ContainingTypeFull} _adapter)");
            w.Indent++;
            w.WriteLine(": global::NadekoBot.Modules.Utility.AiAgent.IAiTool, global::NadekoBot.Services.INService");
            w.Indent--;
            w.WriteLine("{");
            w.Indent++;

            w.WriteLine($"public string Name => {Quote(method.ToolName)};");
            w.WriteLine($"public string Description => {Quote(method.ToolDescription)};");
            w.WriteLine($"public bool IsDataTool => {(method.IsCoreTool ? "false" : "true")};");

            if (!string.IsNullOrEmpty(method.SystemGuidance))
                w.WriteLine($"public string? SystemGuidance => {Quote(method.SystemGuidance!)};");

            w.WriteLine();
            w.WriteLine($"public JsonElement ParameterSchema {{ get; }} = JsonDocument.Parse({Quote(schemaJson)}).RootElement.Clone();");
            w.WriteLine();

            EmitExecuteMethod(w, method);

            w.Indent--;
            w.WriteLine("}");
            w.Flush();
        }

        spc.AddSource($"{className}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitExecuteMethod(IndentedTextWriter w, ToolMethodInfo method)
    {
        w.WriteLine("public async Task<string> ExecuteAsync(AiToolContext _ctx, JsonElement _args)");
        w.WriteLine("{");
        w.Indent++;

        if (method.Parameters.Count > 0)
        {
            w.WriteLine("if (_args.ValueKind != JsonValueKind.Object)");
            w.Indent++;
            w.WriteLine($"_args = global::{JsonOptionsType}.EmptyObject;");
            w.Indent--;
        }

        EmitPermissionChecks(w, method);

        foreach (var p in method.Parameters)
            ParamEmitter.Emit(w, p);

        // Try / catch ToolException -> structured JSON
        w.WriteLine("try");
        w.WriteLine("{");
        w.Indent++;
        EmitAdapterCall(w, method);
        w.Indent--;
        w.WriteLine("}");
        w.WriteLine($"catch (global::{ToolExceptionType} _tex)");
        w.WriteLine("{");
        w.Indent++;
        EmitErrorReturn(w, "_tex.Code", "_tex.Message");
        w.Indent--;
        w.WriteLine("}");

        w.Indent--;
        w.WriteLine("}");
    }

    private static void EmitPermissionChecks(IndentedTextWriter w, ToolMethodInfo method)
    {
        if (method.OwnerOnly)
            EmitPermDenialInline(w, "missing_permission", "ServerOwner",
                "_ctx.User.Guild.OwnerId != _ctx.User.Id");

        foreach (var perm in method.GuildPerms)
            EmitPermDenialInline(w, "missing_permission", perm,
                $"!_ctx.User.GuildPermissions.Has((global::Discord.GuildPermission){perm})");

        foreach (var perm in method.ChannelPerms)
            EmitPermDenialInline(w, "missing_permission", perm,
                $"!_ctx.User.GetPermissions((global::Discord.IGuildChannel)_ctx.SourceChannel)"
                + $".Has((global::Discord.ChannelPermission){perm})");
    }

    private static void EmitPermDenialInline(IndentedTextWriter w, string code, string detail, string condition)
    {
        w.WriteLine($"if ({condition})");
        w.Indent++;
        EmitErrorReturn(w, Quote(code), Quote(detail));
        w.Indent--;
    }

    private static void EmitAdapterCall(IndentedTextWriter w, ToolMethodInfo method)
    {
        var args = BuildAdapterArgList(method);
        var call = $"_adapter.{method.MethodName}({args})";

        if (method.InnerReturnTypeIsVoid)
        {
            w.WriteLine($"await {call};");
            w.WriteLine("return \"{\\\"ok\\\":true}\";");
            return;
        }

        if (method.ReturnsString)
        {
            // Adapter returns Task<string>: pass back to the LLM verbatim.
            w.WriteLine($"return await {call};");
            return;
        }

        w.WriteLine($"var _result = await {call};");
        w.WriteLine($"return System.Text.Json.JsonSerializer.Serialize(_result, global::{JsonOptionsType}.Options);");
    }

    private static string BuildAdapterArgList(ToolMethodInfo method)
    {
        var args = new StringBuilder();
        if (method.HasContext)
            args.Append("_ctx");

        foreach (var p in method.Parameters)
        {
            if (args.Length > 0) args.Append(", ");
            args.Append("_p_").Append(p.Name);
        }
        return args.ToString();
    }

    /// <summary>
    /// Emit a structured-error return ({"error":"&lt;code&gt;","message":"&lt;detail&gt;"}).
    /// codeExpr/messageExpr are C# expressions (already quoted if literal). Used for
    /// permission denials, missing args, parse failures, and ToolException.
    /// </summary>
    internal static void EmitErrorReturn(IndentedTextWriter w, string codeExpr, string messageExpr)
    {
        w.WriteLine($"return System.Text.Json.JsonSerializer.Serialize(new {{ error = {codeExpr}, message = {messageExpr} }});");
    }

    /// <summary>
    /// Quote and JSON-escape an arbitrary string for use as a C# string literal that
    /// will be parsed as JSON at runtime. Handles backslash, quote, CR, LF.
    /// </summary>
    internal static string Quote(string s)
    {
        var sb = new StringBuilder(s.Length + 2);
        sb.Append('"');
        for (var i = 0; i < s.Length; i++)
        {
            var c = s[i];
            switch (c)
            {
                case '\\': sb.Append(@"\\"); break;
                case '"': sb.Append("\\\""); break;
                case '\n': sb.Append(@"\n"); break;
                case '\r': sb.Append(@"\r"); break;
                case '\t': sb.Append(@"\t"); break;
                default:
                    if (c < 0x20)
                        sb.Append("\\u").Append(((int)c).ToString("X4"));
                    else
                        sb.Append(c);
                    break;
            }
        }
        sb.Append('"');
        return sb.ToString();
    }
}
