#nullable enable
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Cloneable;

[Generator]
public class CloneableGenerator : IIncrementalGenerator
{
    private const string PREVENT_DEEP_COPY_KEY_STRING = "PreventDeepCopy";
    private const string EXPLICIT_DECLARATION_KEY_STRING = "ExplicitDeclaration";

    private const string CLONEABLE_NAMESPACE = "Cloneable";
    private const string CLONEABLE_ATTRIBUTE_STRING = "CloneableAttribute";
    private const string CLONE_ATTRIBUTE_STRING = "CloneAttribute";
    private const string IGNORE_CLONE_ATTRIBUTE_STRING = "IgnoreCloneAttribute";

    private const string CLONEABLE_ATTRIBUTE_TEXT = @"// <AutoGenerated/>
using System;

namespace Cloneable
{
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, Inherited = true, AllowMultiple = false)]
    internal sealed class CloneableAttribute : Attribute
    {
        public CloneableAttribute()
        {
        }

        public bool ExplicitDeclaration { get; set; }
    }
}
";

    private const string CLONE_PROPERTY_ATTRIBUTE_TEXT = @"// <AutoGenerated/>
using System;

namespace Cloneable
{
    [AttributeUsage(AttributeTargets.Property, Inherited = true, AllowMultiple = false)]
    internal sealed class CloneAttribute : Attribute
    {
        public CloneAttribute()
        {
        }

        public bool PreventDeepCopy { get; set; }
    }
}
";

    private const string IGNORE_CLONE_PROPERTY_ATTRIBUTE_TEXT = @"// <AutoGenerated/>
using System;

namespace Cloneable
{
    [AttributeUsage(AttributeTargets.Property, Inherited = true, AllowMultiple = false)]
    internal sealed class IgnoreCloneAttribute : Attribute
    {
        public IgnoreCloneAttribute()
        {
        }
    }
}
";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource(CLONEABLE_ATTRIBUTE_STRING,
                SourceText.From(CLONEABLE_ATTRIBUTE_TEXT, Encoding.UTF8));
            ctx.AddSource(CLONE_ATTRIBUTE_STRING,
                SourceText.From(CLONE_PROPERTY_ATTRIBUTE_TEXT, Encoding.UTF8));
            ctx.AddSource(IGNORE_CLONE_ATTRIBUTE_STRING,
                SourceText.From(IGNORE_CLONE_PROPERTY_ATTRIBUTE_TEXT, Encoding.UTF8));
        });

        var cloneableClasses = context.SyntaxProvider.ForAttributeWithMetadataName(
            $"{CLONEABLE_NAMESPACE}.{CLONEABLE_ATTRIBUTE_STRING}",
            static (node, _) => node is ClassDeclarationSyntax,
            static (ctx, _) => GetClassInfo(ctx));

        context.RegisterSourceOutput(cloneableClasses, static (spc, info) =>
        {
            if (info is null)
                return;

            var source = CreateCloneableCode(info.Value);
            spc.AddSource($"{info.Value.ClassName}_cloneable.g.cs",
                SourceText.From(source, Encoding.UTF8));
        });
    }

    private static CloneableClassInfo? GetClassInfo(GeneratorAttributeSyntaxContext ctx)
    {
        var classSymbol = (INamedTypeSymbol)ctx.TargetSymbol;

        var attribute = ctx.Attributes[0];
        var isExplicit = false;
        foreach (var arg in attribute.NamedArguments)
        {
            if (arg.Key.Equals(EXPLICIT_DECLARATION_KEY_STRING))
            {
                isExplicit = (bool)(arg.Value.Value ?? false);
                break;
            }
        }

        var cloneableAttr = ctx.SemanticModel.Compilation
            .GetTypeByMetadataName($"{CLONEABLE_NAMESPACE}.{CLONEABLE_ATTRIBUTE_STRING}");
        var cloneAttr = ctx.SemanticModel.Compilation
            .GetTypeByMetadataName($"{CLONEABLE_NAMESPACE}.{CLONE_ATTRIBUTE_STRING}");
        var ignoreCloneAttr = ctx.SemanticModel.Compilation
            .GetTypeByMetadataName($"{CLONEABLE_NAMESPACE}.{IGNORE_CLONE_ATTRIBUTE_STRING}");

        if (cloneableAttr is null)
            return null;

        var properties = GetCloneableProperties(classSymbol, isExplicit, cloneAttr, ignoreCloneAttr);
        var propertyInfos = ImmutableArray.CreateBuilder<CloneablePropertyInfo>();

        foreach (var prop in properties)
        {
            var isCloneable = IsPropertyCloneable(prop, classSymbol, cloneableAttr);
            propertyInfos.Add(new CloneablePropertyInfo(prop.Name, isCloneable));
        }

        return new CloneableClassInfo(
            classSymbol.ContainingNamespace.ToDisplayString(),
            classSymbol.Name,
            classSymbol.DeclaredAccessibility.ToString().ToLowerInvariant(),
            propertyInfos.ToImmutable());
    }

    private static ImmutableArray<IPropertySymbol> GetCloneableProperties(
        ITypeSymbol classSymbol,
        bool isExplicit,
        INamedTypeSymbol? cloneAttr,
        INamedTypeSymbol? ignoreCloneAttr)
    {
        var builder = ImmutableArray.CreateBuilder<IPropertySymbol>();

        foreach (var member in classSymbol.GetMembers())
        {
            if (member is not IPropertySymbol prop)
                continue;

            if (prop.SetMethod is null || !prop.CanBeReferencedByName)
                continue;

            if (isExplicit)
            {
                if (cloneAttr is not null && HasAttribute(prop, cloneAttr))
                    builder.Add(prop);
            }
            else
            {
                if (ignoreCloneAttr is null || !HasAttribute(prop, ignoreCloneAttr))
                    builder.Add(prop);
            }
        }

        return builder.ToImmutable();
    }

    private static bool IsPropertyCloneable(
        IPropertySymbol prop,
        INamedTypeSymbol classSymbol,
        INamedTypeSymbol cloneableAttr)
    {
        if (SymbolEqualityComparer.Default.Equals(prop.Type, classSymbol))
            return false;

        var attrs = prop.Type.GetAttributes();
        AttributeData? foundAttr = null;
        foreach (var a in attrs)
        {
            if (SymbolEqualityComparer.Default.Equals(a.AttributeClass, cloneableAttr))
            {
                foundAttr = a;
                break;
            }
        }

        if (foundAttr is null)
            return false;

        foreach (var arg in foundAttr.NamedArguments)
        {
            if (arg.Key.Equals(PREVENT_DEEP_COPY_KEY_STRING))
                return !((bool)(arg.Value.Value ?? false));
        }

        return true;
    }

    private static bool HasAttribute(ISymbol symbol, INamedTypeSymbol attributeType)
    {
        foreach (var a in symbol.GetAttributes())
        {
            if (SymbolEqualityComparer.Default.Equals(a.AttributeClass, attributeType))
                return true;
        }

        return false;
    }

    private static string CreateCloneableCode(CloneableClassInfo info)
    {
        var sorted = info.Properties.Sort(
            (a, b) => a.IsCloneable.CompareTo(b.IsCloneable));

        var fastAssignments = new StringBuilder();
        var safeAssignments = new StringBuilder();
        var isFirst = true;

        foreach (var prop in sorted)
        {
            if (!isFirst)
            {
                fastAssignments.Append(",\n");
                safeAssignments.Append(",\n");
            }

            isFirst = false;

            if (prop.IsCloneable)
            {
                fastAssignments.Append($"                {prop.Name} = this.{prop.Name}?.Clone()");
                safeAssignments.Append($"                {prop.Name} = this.{prop.Name}?.CloneSafe(referenceChain)");
            }
            else
            {
                fastAssignments.Append($"                {prop.Name} = this.{prop.Name}");
                safeAssignments.Append($"                {prop.Name} = this.{prop.Name}");
            }
        }

        return $@"using System.Collections.Generic;

namespace {info.Namespace}
{{
    {info.AccessModifier} partial class {info.ClassName}
    {{
        /// <summary>
        /// Creates a copy of {info.ClassName} with NO circular reference checking. This method should be used if performance matters.
        /// 
        /// <exception cref=""StackOverflowException"">Will occur on any object that has circular references in the hierarchy.</exception>
        /// </summary>
        public {info.ClassName} Clone()
        {{
            return new {info.ClassName}
            {{
{fastAssignments}
            }};
        }}

        /// <summary>
        /// Creates a copy of {info.ClassName} with circular reference checking. If a circular reference was detected, only a reference of the leaf object is passed instead of cloning it.
        /// </summary>
        /// <param name=""referenceChain"">Should only be provided if specific objects should not be cloned but passed by reference instead.</param>
        public {info.ClassName} CloneSafe(Stack<object> referenceChain = null)
        {{
            if(referenceChain?.Contains(this) == true) 
                return this;
            referenceChain ??= new Stack<object>();
            referenceChain.Push(this);
            var result = new {info.ClassName}
            {{
{safeAssignments}
            }};
            referenceChain.Pop();
            return result;
        }}
    }}
}}";
    }
}

internal readonly struct CloneableClassInfo : IEquatable<CloneableClassInfo>
{
    public string Namespace { get; }
    public string ClassName { get; }
    public string AccessModifier { get; }
    public ImmutableArray<CloneablePropertyInfo> Properties { get; }

    public CloneableClassInfo(
        string ns,
        string className,
        string accessModifier,
        ImmutableArray<CloneablePropertyInfo> properties)
    {
        Namespace = ns;
        ClassName = className;
        AccessModifier = accessModifier;
        Properties = properties;
    }

    public bool Equals(CloneableClassInfo other)
    {
        if (Namespace != other.Namespace
            || ClassName != other.ClassName
            || AccessModifier != other.AccessModifier
            || Properties.Length != other.Properties.Length)
            return false;

        for (var i = 0; i < Properties.Length; i++)
        {
            if (!Properties[i].Equals(other.Properties[i]))
                return false;
        }

        return true;
    }

    public override bool Equals(object? obj) => obj is CloneableClassInfo other && Equals(other);

    public override int GetHashCode()
    {
        unchecked
        {
            var hash = 17;
            hash = hash * 31 + (Namespace?.GetHashCode() ?? 0);
            hash = hash * 31 + (ClassName?.GetHashCode() ?? 0);
            hash = hash * 31 + Properties.Length;
            return hash;
        }
    }
}

internal readonly struct CloneablePropertyInfo : IEquatable<CloneablePropertyInfo>
{
    public string Name { get; }
    public bool IsCloneable { get; }

    public CloneablePropertyInfo(string name, bool isCloneable)
    {
        Name = name;
        IsCloneable = isCloneable;
    }

    public bool Equals(CloneablePropertyInfo other)
        => Name == other.Name && IsCloneable == other.IsCloneable;

    public override bool Equals(object? obj) => obj is CloneablePropertyInfo other && Equals(other);

    public override int GetHashCode()
    {
        unchecked
        {
            return (Name?.GetHashCode() ?? 0) * 31 + IsCloneable.GetHashCode();
        }
    }
}
